#server:
#  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect
    #   studb
    username: root
    password: root

  servlet:
    multipart:
      #单个文件上传最大速度
      max-file-size: 10MB
      #上传文件总的最大值
      max-request-size: 10MB

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.56.134
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: wang521
    # 连接超时时间（毫秒）
    timeout: 3000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 2000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.qing.tian.test.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true